services:
  app:
    build: .
    container_name: langchain-app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ai_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guyanzhang123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app          # 挂载整个代码，方便调试
      - ./config:/app/config

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guyanzhang123
      POSTGRES_DB: ai_service_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
  
volumes:
  postgres_data:
  redis_data: