services:
  api:
    build: .
    container_name: langchain_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=ai_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=guyanzhang123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app   # 挂载代码，方便调试

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guyanzhang123
      POSTGRES_DB: ai_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
