database:
  host: 8.155.172.25
  port: 5432
  name: ai_service_db
  user: postgres
  password: guyanzhang123

redis:
  host: localhost
  port: 6379
  db: 0
  password: null

model:
  name: mistral
  base_url: http://localhost:11434

log:
  level: INFO        # DEBUG / INFO / WARNING / ERROR
  file: logs/app.log # 日志输出文件路径
  rotation: "10 MB"  # 单文件最大大小，超过后自动切分
  retention: "7 days" # 日志保留时间

api:
  Siliconflow: sk-zskshwraoywkfekdlsqotrzxtpzonsuvdzalcsweetrjbtyo
  name: Qwen/Qwen3-8B
  base_url:  https://api.siliconflow.cn/v1/chat/completions


